### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jjtParadox** [BuiltBrokenModding/MinecraftJUnit#2]
I'd like to use parts of this project in my own personal testing suite. However, only VoltzTestRunner has any kind of license/permissions listed in it. Does the rest of the project fall under any license, or are all rights reserved?

**Comment by DarkGuardsman** [comment]
This is what everything should be licensed under but I have yet to update the files https://github.com/VoltzEngine-Project/Engine/blob/development/license.md which means you can not copy the code. 

However, I can give permission out to use the code. All I need from you is your plans for the code and potentially a link to your project. This way I can document you have permission to use the code as need. Though I would ask you just to use the project as a lib or contribute if you need something changed

**Comment by jjtParadox** [comment]
Good to know! I'll probably just be using this project as a lib and maybe tweak things that need adjustment (without distribution). I'll contribute any major changes I make, too.
